feat(*): support interface{} …
matsuri-tech/json-hidden-marshal pull request #4
Opened 2021-06-04 06:59 UTC by 2222-42

# why

Closes: #3 

# what

- feat(*): support interface{}

2021-06-04 09:51 UTC, myuon requested changes

2021-06-04 09:51 UTC, myuon commented on marshal_test.go
> +				InterfaceHidden interface{} `json:"interface_hidden" hidden:"true"`
go fmtが正しくかかってないようなのでエディタの設定を見直してください

2021-06-07 01:15 UTC, 2222-42 commented on marshal_test.go
> +				InterfaceHidden interface{} `json:"interface_hidden" hidden:"true"`
こちら、修正しました。

また、エディタ設定見直して、保存時にgo fmtをかけるようにしました。

2021-06-07 02:49 UTC, myuon approved these changes

2021-06-07 02:49 UTC, merged